services:

  orla-database:
    image: postgres:15
    environment:
      POSTGRES_DB: orla
      POSTGRES_USER: orla
      POSTGRES_PASSWORD: orla
    ports:
      - "5432:5432"

  orla-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orla-database:5432/orla
      SPRING_DATASOURCE_USERNAME: orla
      SPRING_DATASOURCE_PASSWORD: orla
    ports:
      - "8080:8080"
    depends_on:
      - orla-database
