spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orla
    username: orla
    password: orla
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
server:
  port: 8080
