name: CI

on:
  push:
    branches: [master]

jobs:
  testes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test
        run: mvn -B test